### ISSUE TITLE
hyperapp – 1kbのビューライブラリ

### ISSUE THREAD

**Issue by jorgebucaran** [uzulla/y8-2017-spring-talks#11]
## 表記するお名前、SNSアカウント
[Jorge Bucaran](https://github.com/jbucaran) (ジョージ)
* https://twitter.com/jbucaran
* https://jbucaran.hatenablog.com

## 概要
自分で作った、React.js系の新しいJavaScriptフレームワーク [**hyperapp**](https://github.com/hyperapp/hyperapp) についての話。
* virtual DOMの成り立ちについても少し話す。

## 説明

hyperappは、フロントエンドアプリケーションを構築するための1KBの軽量なJavaScriptライブラリです。WEBアプリケーションでドラッグやクリック、入力、動的な機能などのコンテンツを実装する場合に役に立ちます。シンプルなものでも複雑なものでも、hyperappの使用のみで実装が可能です。さらに1KBと超軽量で、コードも全部で300行ちょっと。ベンチマークもReactと同じくらい。また、他のライブラリやモジュールには依存していません。

## 要求トーク時間
20〜30

## 想定聴講者層
初心者〜中級者

## [初心者枠](http://y8-2017-spring.hachiojipm.org/2017/03/07/recent-status/)が良いですか？
どちらでも

## リモート参加
いいえ

## 録画や写真撮影と、その後の公開
OK

## あなたは暴言などをしない常識を持っていて、このトークで人や法人を悲しませたり怒らせたりせず、平たく言ってネット等でダメな方向に炎上するような行動は慎むことを誓えますか？

はい

## お知らせとなる #1 お知らせスレをSubscribeするなどしてちゃんと読みますか？

済み。

**Comment by uzulla** [comment]
y8主催のuzullaです。
ご応募いただきましたトークを20minで採択させていただきました。
午後の予定ですが、問題がなければ問題なしとご返信いただければ幸いです。
（もししばらくしてもご同意をいただけない場合は、他のトークを繰り上げ当選させて頂く場合がございます）
宜しくお願い致します。

**Comment by jorgebucaran** [comment]
問題なし!!

**Comment by uzulla** [comment]
動画を公開しました！
https://www.youtube.com/watch?v=IgzHEHioNkQ&index=6&list=PLqyYlv12JxkTzXvHqCLk0LmlQXSYzKXIu
